### ISSUE TITLE
Add option to mute

### ISSUE THREAD

**Issue by jamesgillispie** [justinribeiro/lite-youtube#11]
Is it possible to add a param for muted on play?

`<lite-youtube videoid="IJq_8gbiVBg" start="35" mute="1" autoload>`

**Comment by justinribeiro** [comment]
Sure, let me merge #10 and then we'll get that added and in the next release.

**Comment by justinribeiro** [comment]
You should be able to do this now with the use of the `params` option in v0.9.0:
```
<lite-youtube videoid="IJq_8gbiVBg" videoStartAt="35" params="mute=1" autoload>
```
