### ISSUE TITLE
Use of youtube-nocookie for videos

### ISSUE THREAD

**Issue by thetwopct** [justinribeiro/lite-youtube#21]
Hey, this is a nice little component, thanks very much.

I noticed that on Paul's original, he used youtube-nocookie.com to embed the videos, but couldn't see that in this code. Are there issues using the nocookie.com domain maybe (we've experienced a few oddities with it), or what was the reasoning? 

Thanks!

**Comment by MaluNoPeleke** [comment]
I wonder the same.

**Comment by abdonrd** [comment]
What is the difference? Thank you!

**Comment by justinribeiro** [comment]
The attr `nocookie` enables the ability to use the youtube-nocookie domain; the domain itself doesn't set tracking cookies for youtube or doubleclick (at least it doesn't seem to in my brief testing of it).

https://github.com/justinribeiro/lite-youtube/commit/e23de5b0a70fb92ec933b0fd8d3e109e1fdef090#diff-c2f0c4bb74f062c99d3589cb43e6820a4cfb7f8cad9432505b663c06132fb384R272
