### ISSUE TITLE
Requires 2 clicks/taps on Android Chrome/Kiwi Browser

### ISSUE THREAD

**Issue by geekysrm** [justinribeiro/lite-youtube#23]
Using this requires 2 taps to play on Android Chrome browser and Kiwi browser(fork of Chrome).

**Comment by justinribeiro** [comment]
This is an side effect of the `autoplay` policy on mobile which prevents the flag from automatically playing the video after the first tap. This component (or any component really) can't directly control this affect.

To reduce this, you can use the `autoload` attr which will trigger the intersection observer to inject+load, reducing the interaction to one tap.
