### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by greatwitenorth** [justinribeiro/lite-youtube#26]
Looks like there's been several new versions of lite-youtube-embed. Are there any plans to bump this repo to the latest version?

**Comment by justinribeiro** [comment]
This web component doesn't utilize lite-youtube-embed as a dependency and has a varied feature set (intersection observer support) and slightly different accessibility (though both are pretty accessible at this point). 

Is there a feature / fix in Paul's repo that you'd like to see brought over?
