### ISSUE TITLE
Make poster image quality configurable

### ISSUE THREAD

**Issue by greatwitenorth** [justinribeiro/lite-youtube#28]
It looks like `hqdefault` is used by default for the poster image. We need to change this to `maxresdefault` since hq is just too low res for our needs. Would it be possible to add this as a configurable option?

**Comment by kaina-agency** [comment]
I'm looking for this as well. It would be awesome to have a "posterquality" prop (or similar) where you can pass in the string to use, i.e. 'maxresdefault' (or even better, use a style  tag inside the shadow dom in instead of inline style so you can use media queries to set the poster quality).

**Comment by Bandarian** [comment]
I'd love to see this implemented too as I'm using the CDN version and kind of handicapped when it comes to selecting the quality of the placeholder image.

**Comment by nmrose101** [comment]
Any idea if we can get something like this. It is really bad that the picture it is using is really small.

**Comment by justinribeiro** [comment]
Working on it.
