### ISSUE TITLE
Loop / Auto replay not working

### ISSUE THREAD

**Issue by BdgPixel** [justinribeiro/lite-youtube#31]
Hi Guys,

I'm using lite-youtube for embed video https://github.com/justinribeiro/lite-youtube

currently i add in home page using this code in shopify

<lite-youtube videoid="Dv35Uu4iidw" params="?playlist=Dv35Uu4iidw&amp;loop=1" autoload="" loop=""></lite-youtube>

but can't auto replay when video end, any one can help?

Thanks,
Reza

**Comment by justinribeiro** [comment]
You have to set the loop and playlist params (where the playlist param is the same id as the video.

Example:
```
<lite-youtube videoid="guJLfqTFfIw" params="loop=1&playlist=guJLfqTFfIw"></lite-youtube>
```
