### ISSUE TITLE
params function not working

### ISSUE THREAD

**Issue by Bandarian** [justinribeiro/lite-youtube#32]
Hey guys,

Been implementing this wonderful lite-youtube solution on my clients site to much success. Recently when asked to add the rel=0 param to the videos I followed the instructions listed and nothing happens. I also tried a load of other parameters to no success either. Could anyone assist me in getting the params to work :) 

`<lite-youtube videoid="arygCLXYB7Y" params="rel=0"> </lite-youtube>`

**Comment by justinribeiro** [comment]
> I followed the instructions listed and nothing happens

Appears to be working fine; the parameters are appended to the YouTube iframe src target as expected. What are you expecting to occur? Do you not see the params at the end of the src url as in the screenshot below?

![ss-2021-08-20-justinribeiro-001](https://user-images.githubusercontent.com/643503/130252449-c32607c6-431c-4794-80e9-b47725c1513e.png)

**Comment by Bandarian** [comment]
Hey Justin,

Thanks for getting back to me. I can see that it's working on the shot you sent me. However, on inspecting the site where I've input the code it doesn't appear to be affixing itself to the end of the src link.
I've put the code inside an HTML embed inside my Webflow site [here](https://melbournefunctionalmedicine.com.au/team-members/courtney-tanner) please take a look if you wish.

![Screenshot (91)](https://user-images.githubusercontent.com/64462886/130301786-6e652504-f61b-45f7-aa98-9fca958d6538.png)

Thanks so much for your help

**Comment by justinribeiro** [comment]
You're using an old version that didn't support the `params` attr:
![ss-2021-08-20-justinribeiro-005](https://user-images.githubusercontent.com/643503/130303811-3e98ee04-69a6-468d-9b10-2fc3e99f16ba.png)


update your include line to:
```
<script type="module" 
src="https://cdn.jsdelivr.net/npm/@justinribeiro/lite-youtube@0.9.1/lite-youtube.js">
</script> 
```
and you'll be golden (seen her with an devTools override):
![ss-2021-08-20-justinribeiro-004](https://user-images.githubusercontent.com/643503/130303827-cd566ae3-fa32-474b-9928-f01e45a9c644.png)

**Comment by Bandarian** [comment]
Awesome!

Thanks so much mate appreciate the help.

:)

**Comment by yeaske** [comment]
The CDN link in readme still shows old version. I guess that is causing this confusion.
