### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by allesan** [justinribeiro/lite-youtube#33]
I have a trouble with Firefox not showing anything
I'm using FF 91 and 0.9.1 of the lite youtube

If I turn of position: absolute; for #frame, #fallbackPlaceholder, iframe then image is shown but video is being loaded under the picture.

**Comment by justinribeiro** [comment]
I'm not able to duplicate this in FF91 (see attached video). Do you have any specific code to reproduce the issue?

https://user-images.githubusercontent.com/643503/130251828-5a1acd4e-df29-4e5a-b92d-65abe1f9b00f.mp4

**Comment by allesan** [comment]
Sorry, nothing specific, just basic example.
I'll try to investigate some more, my CSS and HTML.
