### ISSUE TITLE
Lazy or Eager loading

### ISSUE THREAD

**Issue by andreapernici** [justinribeiro/lite-youtube#42]
Is it possible to introduce a new parameter to decide if the preview image should be loaded with loading=lazy or loading=eager?

**Comment by andreapernici** [comment]
Line 56 added
```

    get loading() {
        return this.getAttribute('loading') || 'lazy';
    }
    set loading(name) {
        this.setAttribute('loading', name);
    }
```

then added

```
    initImagePlaceholder() {
        ....
        this.domRefImg.fallback.setAttribute('loading', `${this.loading}`);
        ....
    }
```

looks like it works.

**Comment by justinribeiro** [comment]
I can add `posterloading`, since this would only effect the image poster (and not the default iframe behavior).

**Comment by justinribeiro** [comment]
Added with 66e87517acb09f48a8387124b0e8cb21b00e940a, will be in v1.3 end of week.

**Comment by andreapernici** [comment]
Thanks Justin
