### ISSUE TITLE
position absolute display issues - missing left: 0;

### ISSUE THREAD

**Issue by LarsPeterson** [justinribeiro/lite-youtube#46]
![image](https://user-images.githubusercontent.com/25396567/146832637-cb0856df-5510-43b9-ad46-62bcf0a20149.png)

![image](https://user-images.githubusercontent.com/25396567/146833807-6607feb5-b8d9-4436-bc59-e0de85a69e80.png)

Issues are caused by position absolute on the following css:

![image](https://user-images.githubusercontent.com/25396567/146833934-5c65b03b-6e07-422f-bfae-3171f2a5e2a1.png)

![image](https://user-images.githubusercontent.com/25396567/146833975-40475d6f-5254-4e74-b347-2188a44dd01f.png)

HERE IS THE FIX:

![image](https://user-images.githubusercontent.com/25396567/146834047-51e77ce9-e13e-4dd0-bc7a-62853a6aec5a.png)

![image](https://user-images.githubusercontent.com/25396567/146834075-385772ba-f7c5-4dac-b8aa-7704696486b2.png)

![image](https://user-images.githubusercontent.com/25396567/146834089-7975040d-ba74-4d68-8b70-6d896d431d5f.png)

Hi @justinribeiro, please advise.

**Comment by LarsPeterson** [comment]
I'm not sure if I am doing something wrong.

I can't edit the CSS since its the shadow dom. How to adjust?

**Comment by LarsPeterson** [comment]
Looks like a previous issue also mentions this CSS issue (left: 0), I apologize for duplicating the issue but it looks like it wasn't resolved.

https://github.com/justinribeiro/lite-youtube/issues/43

**Comment by justinribeiro** [comment]
It's merged, but needs a release. I'll cut it this afternoon. :+1:

**Comment by justinribeiro** [comment]
Fixed in v1.3.1 https://github.com/justinribeiro/lite-youtube/releases/tag/v1.3.1 now on NPM.
