### ISSUE TITLE
Issue with HDR Videos Being Displayed using lite-youtube

### ISSUE THREAD

**Issue by ryanrbftp** [justinribeiro/lite-youtube#53]
Hi there,

We have used the lite-youtube code for some time now.  All works wonderfully.  

However, we have an issue when embedding videos available in **HDR**

The videos are completely washed out and much too bright.

Example of lite-youtube embed with HDR video:
<img width="864" alt="Screen Shot 2022-02-09 at 21 58 25" src="https://user-images.githubusercontent.com/4421291/153297177-bd2dfe5e-15c5-4b14-91e0-ff5c419d16be.png">

What the actual video should look like (from YouTube):

<img width="1316" alt="Screen Shot 2022-02-09 at 21 59 32" src="https://user-images.githubusercontent.com/4421291/153297315-674cf0dd-d27f-4efa-bbb9-e30b364790f8.png">

We tested with a standard YouTube IFRAME embed of the same video and all works just fine with HDR - it displays correctly.

We were testing on Chrome (latest stable).

**Comment by justinribeiro** [comment]
Humm, that is odd. I've only seen that behavior once before and it was resolved with a point patch in M87 (it seemingly happened randomly, though I don't know if there was a ticket for it upstream). As there isn't anything lite-youtube had changed recently that would cause this, I'll do a little digging and investigate.

**Comment by nmrose101** [comment]
That is actually part of the video. Best way to fix this is to go to final cut and use the HDR filter.

**Comment by ryanrbftp** [comment]
> That is actually part of the video. Best way to fix this is to go to final cut and use the HDR filter.

I don't think this comment makes any sense.  As you can see above, the differences between YouTube direct player and the yt-lite embed on the _same video_.

@justinribeiro - any update on a fix for this?  All the best and thank you for looking into it.  Also, we'd be happy to make a donation to your project to ensure continued support of this package.  Could you let us know the details?

**Comment by nmrose101** [comment]
This is 100% a video problem. Some players like HDR and some don't (Instagram hates it). Here is one article I just googled for you on how to fix this.

https://www.provideocoalition.com/editing-iphone-hdr-video-in-final-cut-pro/

**Comment by ryanrbftp** [comment]
@nmrose101 

YouTube is fine with HDR.

It's a full, correctly rendered, and produced HDR video we uploaded to YT.  The video works fine on YouTube:
https://www.youtube.com/watch?v=LMi2rjziSFU

But not in an lite-youtube embed/draw:
https://www.simshack.net/products/handley-page-hampden-x-plane-1887

@justinribeiro - it seems with the latest Chrome stable the video does not render at all and we just get black.  Just tested a native YT IFRAME embed for the same video and all is fine.

**Comment by ryanrbftp** [comment]
Was there any update on this?

Another live example:
https://www.simshack.net/products/bae-146-146-professional-aircraft-add-on-msfs-1896

Many thanks.

**Comment by justinribeiro** [comment]
Going through the backlog, I see this still open. I tested the above against the latest and the HDR versions seem to render without issue in M131 builds of FF and Chrome. Closing.
