### ISSUE TITLE
[bug] Create multiple iframe when click on frame

### ISSUE THREAD

**Issue by abdonrd** [justinribeiro/lite-youtube#7]
Create multiple iframe when click on frame

Video:

![Nov-26-2019 19-20-57](https://user-images.githubusercontent.com/1007051/69661030-e52d5380-1081-11ea-99fc-bc534f33e805.gif)

That same `before` `frame` does not allow to click on the title of the YouTube video.

**Comment by justinribeiro** [comment]
Cheers! Fixed in version 0.6.1.

**Comment by abdonrd** [comment]
Thanks @justinribeiro!

Now it doesn't create a new iframe, but it still hides the title of the YouTube video. 😕

**Comment by justinribeiro** [comment]
Ahh, I see it. Fix inbound.

**Comment by justinribeiro** [comment]
::before header now properly hides, allowing title and buttons to display correctly. Published as v0.6.2.

**Comment by abdonrd** [comment]
Thanks @justinribeiro! 👏
