### ISSUE TITLE
CDN: Uncaught SyntaxError: Unexpected token 'export' (at lite-youtube.js:1:1)

### ISSUE THREAD

**Issue by Juc1** [justinribeiro/lite-youtube#86]
I am using the CDN - my HTML [page source](https://phpstack-819629-3338850.cloudwaysapps.com/node/2) has

`<lite-youtube videoid="guJLfqTFfIw"></lite-youtube>`
`<script src="https://cdn.jsdelivr.net/npm/@justinribeiro/lite-youtube@1.5.0/lite-youtube.js"></script>` 

but no video is rendered and console has error 
`Uncaught SyntaxError: Unexpected token 'export' (at lite-youtube.js:1:1)`

Any ideas please?

**Comment by justinribeiro** [comment]
You're missing the the type=module on the script tag:

```html
<script type="module" src="https://cdn.jsdelivr.net/npm/@justinribeiro/lite-youtube@1.5.0/lite-youtube.js"></script>
```

**Comment by Juc1** [comment]
Ok fixed, thank you :)

**Comment by Juc1** [comment]
@justinribeiro my SEO audit tool semrush is complaining that the CDN link is not minified - would it be possible for you to add a minified version to the CDN?

**Comment by justinribeiro** [comment]
Just add `.min` and it'll minimize.

```html
<script type="module" src="https://cdn.jsdelivr.net/npm/@justinribeiro/lite-youtube@1.5.0/lite-youtube.min.js"></script>
```
![image](https://user-images.githubusercontent.com/643503/231219725-c77f2edc-8de2-44b9-aaad-039a7d9ce75b.png)

**Comment by Juc1** [comment]
@justin yes that works thank you
