### ISSUE TITLE
Google indexing errors

### ISSUE THREAD

**Issue by readtedium** [justinribeiro/lite-youtube#87]
Hey, I’m a huge fan of this project, which saves a ton of loading time on my site when it comes to embeds. However, I noticed that the script created an indexing problem that Google Search Console pointed out:

<img width="936" alt="Screen Shot 2023-04-03 at 4 23 14 PM" src="https://user-images.githubusercontent.com/470216/229619143-0fa59790-3159-4b98-af39-df06b93ceb2a.png">
<img width="933" alt="Screen Shot 2023-04-03 at 4 23 29 PM" src="https://user-images.githubusercontent.com/470216/229619144-26632ba0-b858-4db6-abee-a64ead0b8597.png">

Essentially, it is no longer tagging these videos as videos.

I don’t know if there is an easy solution to this, but it appears that the use of this script is creating unintentional side effects that are proving potentially damaging from an SEO standpoint. Any thoughts on a potential common ground here?

**Comment by justinribeiro** [comment]
Hi! Humm, it's an interesting conundrum, though the newer report errors are a bit confusing (e.g., the "Video not found on host service" would imply that it sees a video but that video is not index-able or crawl-able, ala usually a private video on YouTube). The "prominent video" error I see from time to time, though that's because of placement and size rules.

That said, I suspect I can solve for this. Let me run a couple tests this week, see if I can't make a couple tweaks. :+1:

**Comment by katiedeangelis** [comment]
> That said, I suspect I can solve for this. Let me run a couple tests this week, see if I can't make a couple tweaks. 👍

Hey @justinribeiro just wanted to check in a see if this is something that you've been able to look into?

**Comment by oncode** [comment]
@katiedeangelis Likely same issue as here https://github.com/paulirish/lite-youtube-embed/issues/105

**Comment by katiedeangelis** [comment]
> @katiedeangelis Likely same issue as here [paulirish/lite-youtube-embed#105](https://github.com/paulirish/lite-youtube-embed/issues/105)

Yes, it absolutely is the same issue!

**Comment by readtedium** [comment]
How frustrating. On the plus side, it appears it may be solvable. Fingers crossed!

**Comment by Dade88** [comment]
Would it be possible to have an option which autoloads the iframe from lite-youtube on load when Google bot visits the page?

I am doing several tests to find out if the videos can really be indexed with lite-youtube but so far the results are inconclusive.
