### ISSUE TITLE
Remove `#frame::before`?

### ISSUE THREAD

**Issue by elibarzilay** [justinribeiro/lite-youtube#94]
It took me a while to realize that the top shadow effect is coming from here and not from youtube...

Initially I thought about adding another attribute to specify the gradient, or the whole `::before` etc -- but then I remembered this from `CONTRIBUTING.md`:

> Anything that adds bloat or perf loss won't be accepted [...]

So for myself, I just nuked it, but following the same motto, it seems fitting to drop it -- if anyone wants to see a shadow, they can add one themselves, no?

**Comment by justinribeiro** [comment]
The reason it's there is that it holds the stock YouTube embed look and
feel. In terms of bloat/perf loss, ::before doesn't add weight to the perf
in the traces so I'm inclined to leave it as is.

**Comment by elibarzilay** [comment]
OK, that makes sense (and it *did* take me a while to realize where that shadow was coming from since it did feel like it's what youtube hands out...).

Would you mind adding some `posterbare` option that will drop it?

**Comment by elibarzilay** [comment]
Ping on this?
