### ISSUE TITLE
Poster Fallback JPG doesn't work in 1.5.0 with FF

### ISSUE THREAD

**Issue by arcivanov** [justinribeiro/lite-youtube#97]
At the bottom of the https://pybuilder.io/ there is a "Watch the Presentation" section with an embedded YT.

We switched to lite-youtube (thank you!) but encountered that the JPG fallback fails.

The switch: https://github.com/pybuilder/pybuilder.github.io/commit/9f01bc98139e0f26d19513d6d92ef1359b6dd82e
The fallback JPG exists but WEBP does not: 

![JPEG](https://i.ytimg.com/vi/iQU18hAjux4/hqdefault.jpg) 

![WEBP](https://i.ytimg.com/vi_webp/iQU18hAjux4/hqdefault.webp)

Yet the poster JPG is never loaded and only "missing WEBP" image can be seen:

![image](https://github.com/justinribeiro/lite-youtube/assets/5355666/548f2ac1-77c2-4d2e-b379-bcc002c06291)

I suspect that this is because the 404 returns the actual image **along** the 404:

![image](https://github.com/justinribeiro/lite-youtube/assets/5355666/d741ec05-869f-4ad2-a155-3bb2c5a654de)

Is there a way to make fallback reject the image in the 404 and actually fall back?

**Comment by justinribeiro** [comment]
The picture element doesn't support flipping the source in the case of a 404 or other error per the spec. To accomplish this, I'd have to add a little sugar to it to listen for the 404 and strip the source elem from picture. Let me see if I can sort that. :+1:

**Comment by arcivanov** [comment]
Thank you!

**Comment by arcivanov** [comment]
There is another option - make JPEG primary and WEBP a fallback. Would that work as an easier fix?

**Comment by arcivanov** [comment]
Any updates on this?

**Comment by sgrund14** [comment]
running to this as well!

**Comment by mrwweb** [comment]
Hoping there can be a solution for this! Just a note that this issue appears in Chrome as well and I don't think it's browser specific.
