### ISSUE TITLE
Thumbnails not rendering

### ISSUE THREAD

**Issue by bmrobson101** [justinribeiro/lite-youtube#98]
I'm having issues getting my thumbnails to render using this component. My videoID is correct so I'm not sure why it's not working

**Comment by arcivanov** [comment]
Related to #97?

**Comment by bmrobson101** [comment]
No, I'm not even getting a generic image like that. It just looks like this:
![Capture](https://github.com/justinribeiro/lite-youtube/assets/138937403/598a5165-dfe2-4b50-a8cc-2a045a010acd)

And this is my codebase:
![Capture](https://github.com/justinribeiro/lite-youtube/assets/138937403/e46224fa-2f8c-4454-8813-e164ad467d3c)

**Comment by bmrobson101** [comment]
I should also note that this is in an Angular project. Tried doing this with raw HTML and it worked fine
