### ISSUE TITLE
Uncaught (in promise) Error: Orphaned iframed

### ISSUE THREAD

**Issue by looloosha** [justinribeiro/lite-youtube#99]
The library works without a hitch but I am getting an error in my console when the iframe is loaded into DOM.
![image](https://github.com/justinribeiro/lite-youtube/assets/9650847/8cd968f4-6f20-49de-a111-a821af9e1914)

Any thoughts on what this could be?

Here's my HTML structure:
`<section id="demo-links" class="container-fluid">
	
	<style>
		.lite-youtube-fallback {
			aspect-ratio: 16 / 9; /* matches YouTube player */
			display: flex;
			justify-content: center;
			align-items: center;
			flex-direction: column;
			gap: 1em;
			padding: 1em;
			background-color: #000;
			color: #fff;
			text-decoration: none;
		}

		/* right-facing triangle "Play" icon */
		.lite-youtube-fallback::before {
			display: block;
			content: '';
			border: solid transparent;
			border-width: 2em 0 2em 3em;
			border-left-color: red;
		}

		.lite-youtube-fallback:hover::before {
			border-left-color: #fff;
		}

		.lite-youtube-fallback:focus {
			outline: 2px solid red;
		}
	</style>

	<div class="container section-pad">
		<lite-youtube videotitle="Test"
					  videoid="iPBRfWAbf7E"
					  posterquality="maxresdefault"
					  >
			<a class="lite-youtube-fallback" href="https://www.youtube.com/watch?v=iPBRfWAbf7E">Watch on YouTube: Test"</a>
		</lite-youtube>
	</div>
</section>

<script type="module" src="https://cdn.jsdelivr.net/npm/@@justinribeiro/lite-youtube@@1.5.0/lite-youtube.js"></script>`

Any ideas what this could be? I can't find ANYTHING online :(

**Comment by justinribeiro** [comment]
The "web-client-content-script.js" is typically part of a browser extension (from which extension, I do not know in your case); based on the code you shared, things work fine (well, you should remove the double "@@"'s for the script).

**Comment by drew-forsberg** [comment]
Thanks, Justin! FYI, the double @ is just because this code is in an ASP.NET Razor page, which requires @@ to escape the original single @.

**Comment by looloosha** [comment]
Turns out you were right about it being an extension causing the issue! It was LastPass extension in this case. Thank you tremendously @justinribeiro !!!
